export const skillsData =[
    {
label:"FRONTEND",
data: [
    {
        skillName:"HTML",
        percentage:"90",
    },
    {
        skillName:"CSS",
        percentage:"85",
    },
    {
        skillName:"React.js",
        percentage:"60",
    },
],
},
{
    label:"BACKEND",
    data:[
        {
            skillName:"JAVA",
            percentage:"70",
        },
        {
            skillName:"node,js",
            percentage:"80",
        },
        {
            skillName:"PYTHON",
            percentage:"20",
        },
    ],
},
{
    label:"DATABASESS",
    data:[
       
        {
            skillName:"Postman",
            percentage:"90",
        },
        {
            skillName:"mongodb",
            percentage:"80",
        },
        {
            skillName:"sql",
            percentage:"60",
        },
        
    ]
}
]